server:
  port: 8080

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8081/
          predicates:
            - Path=/orders/**
        - id: inventory-service
          uri: http://localhost:8082/
          predicates:
            - Path=/inventory/**

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
